export const TOKEN_KEY = 'AUTH_ACCESS_TOKEN'
export const FONT_FAMILY_CN = '__FONT_FAMILY_CN__'
export const PINYIN_COLORED = '__PINYIN_COLORED__'
export const HIEROGLYPH_WORD_VARIANT = '__HIEROGLYPH_WORD_VARIANT__'
