export default defineAppConfig({
  titleTemplate: '%s', 
  name: 'chinisik',
  link: [
    { rel: 'apple-touch-icon', sizes: '180x180', href: '/icons/apple-touch-icon.png' },
    { rel: 'icon', type: 'image/png', sizes: '32x32', href: '/icons/favicon-32x32.png' },
    { rel: 'icon', type: 'image/png', sizes: '16x16', href: '/icons/favicon-16x16.png' },
    { rel: 'manifest', href: '/icons/manifest.webmanifest' },
    { rel: 'mask-icon', href: '/icons/safari-pinned-tab.svg', color: '#0d1117' },
    { rel: 'shortcut icon', href: '/icons/favicon.ico' },
  ],
  meta: [
    { name: 'msapplication-config', content: '/icons/browserconfig.xml' },
    { name: 'viewport', content: 'viewport-fit=cover, initial-scale=1, maximum-scale=1, user-scalable=no' },
    { name: 'title', content: 'chinisik' },
    { name: 'keywords', content: 'китайский язык, учить китайский, иероглифы, пиньинь, HSK, китайский словарь, грамматика китайского' },
    { hid: 'description', name: 'description', content: 'chinisik' },
    { property: 'og:title', content: 'Чайнизик' },
    { property: 'og:description', content: 'Место для возносения до уровня ТанСана! Познай мир иероглифов чтобы уверено сказать - нихао ни женгуо рен ма!' },
    { property: 'twitter:title', content: 'Чайнизик' },
    { property: 'twitter:description', content: 'Место для возносения до уровня ТанСана! Познай мир иероглифов чтобы уверено сказать - нихао ни женгуо рен ма!' },
    { property: 'twitter:image', content: 'https://chinisik.ru.app/open-graph.png' },
    { property: 'og:url', content: 'https://chinisik.ru.app' },
    { property: 'og:image', content: 'https://chinisik.ru.app/open-graph.png' },
    { property: 'og:image:width', content: '400' },
    { property: 'og:image:height', content: '400' },
    { name: 'twitter:card', content: 'summary' },
    { name: 'og:locale', content: 'ru_RU' },
    { name: 'twitter:locale', content: 'ru' },
  ],
})
